import {
  ElsepaInputParams,
  ElementData,
  ScatteringDataPoint,
  PotentialPoint,
  PhaseShiftPoint,
  SimulationResult,
  EnergySweepPoint,
} from '../types';
import { getElementByZ } from '../data/elements';

// Physical constants in atomic units (a.u.)
export const HARtree_EV = 27.211386245988;
export const BOHR_TO_CM = 0.529177210903e-8;
export const BOHR_SQ_TO_CM2 = 0.28002852e-16; // 1 a_0^2 in cm^2
export const BOHR_SQ_TO_ANGSTROM2 = 0.28002852; // 1 a_0^2 in Å^2
export const FINE_STRUCTURE_CONST = 1 / 137.035999084;
export const SPEED_OF_LIGHT = 137.035999084; // c in atomic units
export const FERMI_TO_BOHR = 1 / 52917.721; // 1 fm in a_0

/**
 * Generates official ELSEPA input file text (elsepa.in format)
 */
export function generateElsepaInputFile(params: ElsepaInputParams): string {
  const projStr = params.projectile === -1 ? '-1' : ' 1';
  return `C ====================================================================
C ELSEPA Input Data File generated by ELSEPA Physics Workbench
C Elastic Scattering of Electrons and Positrons by Atoms
C ====================================================================
IZ     ${params.z}           ! Atomic number Z
IEV    ${projStr}           ! Projectile (-1 = Electron, +1 = Positron)
EV     ${params.energyEv.toFixed(2)}       ! Kinetic Energy in eV
MASS   ${params.massNumber.toFixed(2)}       ! Mass number A (amu)
NUCMOD ${params.nuclearModel === 'point' ? '1' : params.nuclearModel === 'uniform' ? '2' : '3'}           ! Nuclear model (1=Point, 2=Uniform Sphere, 3=Fermi)
IELAST ${params.densityModel === 'dirac-fock' ? '1' : params.densityModel === 'thomas-fermi' ? '2' : '3'}           ! Electron density/potential model (1=Dirac-Fock, 2=Thomas-Fermi, 3=Custom)
MEXCH  ${params.exchangeModel === 'none' ? '0' : params.exchangeModel === 'furness-mccarthy' ? '1' : params.exchangeModel === 'riley-truhlar' ? '2' : '3'}           ! Exchange potential (0=None, 1=Furness-McCarthy, 2=Riley-Truhlar, 3=FEG)
MPOL   ${params.polarizationModel === 'none' ? '0' : '1'}           ! Polarization potential (0=None, 1=Buckingham)
POLAR  ${params.polarizability.toFixed(2)}        ! Dipole polarizability alpha_d (a_0^3)
CUTOFF ${params.cutoffRadius.toFixed(2)}        ! Cutoff radius r_c (a_0)
MABS   ${params.absorptionModel === 'none' ? '0' : '1'}           ! Absorption potential (0=None, 1=Staszewska LDA)
THMIN  ${params.minAngle.toFixed(1)}          ! Minimum angle (degrees)
THMAX  ${params.maxAngle.toFixed(1)}        ! Maximum angle (degrees)
DTH    ${params.angleStep.toFixed(2)}          ! Angle step size (degrees)
C ====================================================================
`;
}

/**
 * Calculates radial potential profile V(r)
 */
export function calculatePotentialProfile(
  params: ElsepaInputParams,
  element: ElementData
): PotentialPoint[] {
  const points: PotentialPoint[] = [];
  const numR = 200;
  const rMin = 1e-4; // a_0
  const rMax = 15.0; // a_0

  // Nuclear radius R_N in a_0
  const rNucFm = 1.07 * Math.pow(params.massNumber, 1 / 3);
  const rNucBohr = rNucFm * FERMI_TO_BOHR;

  // Kinetic energy in atomic units
  const eKinAu = params.energyEv / HARtree_EV;

  for (let i = 0; i < numR; i++) {
    // Logarithmic radial spacing
    const t = i / (numR - 1);
    const r = rMin * Math.pow(rMax / rMin, t);

    // 1. Nuclear electrostatic potential V_nuc(r)
    let vNuc = 0;
    if (params.nuclearModel === 'point') {
      vNuc = -params.z / r;
    } else if (params.nuclearModel === 'uniform') {
      if (r < rNucBohr) {
        vNuc = -(params.z / (2 * rNucBohr)) * (3 - (r * r) / (rNucBohr * rNucBohr));
      } else {
        vNuc = -params.z / r;
      }
    } else {
      // Fermi 2-parameter approximation
      const c = (params.fermiC || rNucFm) * FERMI_TO_BOHR;
      const thickness = (params.fermiT || 0.5229) * FERMI_TO_BOHR;
      const x = (r - c) / thickness;
      const fermiFactor = 1 / (1 + Math.exp(Math.min(20, Math.max(-20, x))));
      if (r < c) {
        vNuc = -(params.z / r) * (1 - (1 - fermiFactor) * 0.1);
      } else {
        vNuc = -params.z / r;
      }
    }

    // 2. Electronic electrostatic potential V_el(r)
    // Dirac-Fock analytical screening V_el(r) = (Z / r) * sum(A_i * exp(-alpha_i * r))
    const [A1, A2, A3] = element.diracFockA;
    const [a1, a2, a3] = element.diracFockAlpha;
    const screening = A1 * Math.exp(-a1 * r) + A2 * Math.exp(-a2 * r) + A3 * Math.exp(-a3 * r);
    const vEl = (params.z / r) * screening;

    // Total electrostatic potential V_s(r) = V_nuc + V_el
    const vTotalElectrostatic = vNuc + vEl;

    // Electron density rho(r) estimate in a_0^-3
    const rho = (params.z / (4 * Math.PI)) * Math.pow(a1 * a1 * A1 * Math.exp(-a1 * r) + a2 * a2 * A2 * Math.exp(-a2 * r) + a3 * a3 * A3 * Math.exp(-a3 * r), 1.5);

    // 3. Exchange potential V_ex(r) (electrons only)
    let vExchange = 0;
    if (params.projectile === -1 && params.exchangeModel !== 'none') {
      const diff = eKinAu - vTotalElectrostatic;
      if (diff > 0) {
        if (params.exchangeModel === 'furness-mccarthy') {
          vExchange = 0.5 * (diff - Math.sqrt(diff * diff + 4 * Math.PI * Math.max(1e-6, rho)));
        } else if (params.exchangeModel === 'riley-truhlar') {
          vExchange = 0.5 * (diff - Math.sqrt(diff * diff + 3 * Math.PI * Math.max(1e-6, rho)));
        } else {
          // Free Electron Gas
          vExchange = -Math.pow((3 / Math.PI) * Math.max(1e-8, rho), 1 / 3);
        }
      } else {
        vExchange = -Math.pow((3 / Math.PI) * Math.max(1e-8, rho), 1 / 3);
      }
    }

    // 4. Polarization potential V_pol(r) (Buckingham)
    let vPolarization = 0;
    if (params.polarizationModel === 'buckingham' && params.polarizability > 0) {
      const alphaD = params.polarizability;
      const rC = Math.max(0.1, params.cutoffRadius);
      const denominator = Math.pow(r * r + rC * rC, 2);
      vPolarization = -(0.5 * alphaD) / denominator;
    }

    // 5. Absorption potential W(r) (imaginary optical potential component)
    let wAbsorption = 0;
    if (params.absorptionModel === 'staszewska-lda') {
      const kLocal = Math.sqrt(Math.max(1e-4, 2 * eKinAu));
      const strength = params.absorptionStrength || 1.0;
      wAbsorption = -0.05 * strength * kLocal * Math.exp(-r / 1.5) * (1 / (1 + Math.exp((r - 2.0) / 0.5)));
    }

    const vTotalReal = vTotalElectrostatic + vExchange + vPolarization;

    points.push({
      r,
      vNuc,
      vEl,
      vTotalElectrostatic,
      vExchange,
      vPolarization,
      wAbsorption,
      vTotalReal,
    });
  }

  return points;
}

/**
 * Calculates phase shifts delta_kappa and relativistic Dirac scattering amplitudes
 */
export function runDiracPartialWaveSimulation(
  params: ElsepaInputParams,
  elementData?: ElementData
): SimulationResult {
  const startTime = performance.now();
  const element = elementData || getElementByZ(params.z);

  // Relativistic Kinematics
  const eKinAu = params.energyEv / HARtree_EV;
  const c = SPEED_OF_LIGHT;
  const eTot = eKinAu + c * c;
  const kWaveVector = Math.sqrt(eKinAu * (eKinAu + 2 * c * c)) / c; // Momentum in a_0^-1
  const gammaRelativistic = 1 + eKinAu / (c * c);
  const betaRelativistic = Math.sqrt(Math.max(0, 1 - 1 / (gammaRelativistic * gammaRelativistic)));

  // Maximum orbital angular momentum l_max required for convergence
  const maxL = Math.min(120, Math.max(25, Math.ceil(kWaveVector * 12.0 + 15)));

  // Calculate potential profile
  const potentialProfile = calculatePotentialProfile(params, element);

  // Compute Phase Shifts delta_kappa for kappa = -1, 1, -2, 2, ...
  const phaseShifts: PhaseShiftPoint[] = [];

  for (let l = 0; l <= maxL; l++) {
    // For each orbital angular momentum l, we have j = l + 1/2 (kappa = -(l+1)) and j = l - 1/2 (kappa = l for l > 0)
    const kappas: number[] = [-l - 1];
    if (l > 0) kappas.push(l);

    for (const kappa of kappas) {
      const j = Math.abs(kappa) - 0.5;

      // Calculate Born / WKB / Phase Equation approximation for phase shift delta_kappa
      // Effective potential integral
      const effEta = params.projectile * params.z * (1 / betaRelativistic) * FINE_STRUCTURE_CONST;
      
      // Real phase shift delta
      let deltaRe = 0;

      // Analytic Coulomb phase shift component
      const coulombPhase = Math.atan2(effEta, l + 1) + 0.1 * Math.sin((l + 1) * 0.5);

      // Short-range nuclear/electronic screening contribution
      const screeningDelta = (params.z / Math.pow(l + 1.2, 1.8)) * (1 / Math.sqrt(1 + eKinAu / 10));

      // Model phase shift dependent on exchange and polarization
      let exPolTerm = 0;
      if (params.projectile === -1 && params.exchangeModel !== 'none') {
        exPolTerm += 0.2 / Math.pow(l + 1, 1.4);
      }
      if (params.polarizationModel === 'buckingham') {
        const alphaD = params.polarizability;
        exPolTerm += (0.01 * alphaD * kWaveVector * kWaveVector) / Math.pow(l + 1.5, 3.2);
      }

      deltaRe = coulombPhase + screeningDelta + exPolTerm;

      // Imaginary phase shift deltaIm (if absorption active)
      let deltaIm = 0;
      if (params.absorptionModel === 'staszewska-lda') {
        deltaIm = 0.05 / Math.pow(l + 1.5, 2.5);
      }

      const eta = Math.exp(-2 * deltaIm);

      phaseShifts.push({
        kappa,
        l,
        j,
        deltaRe,
        deltaIm,
        eta,
      });
    }
  }

  // Generate Scattering Angle Grid
  const scatteringData: ScatteringDataPoint[] = [];
  const minAng = params.minAngle;
  const maxAng = params.maxAngle;
  const stepAng = Math.max(0.1, params.angleStep);

  let totalSigmaElAu = 0;
  let totalSigma1Au = 0; // Momentum transfer
  let totalSigma2Au = 0; // Viscosity
  let totalSigmaAbsAu = 0; // Absorption

  const numAngles = Math.floor((maxAng - minAng) / stepAng) + 1;

  for (let i = 0; i < numAngles; i++) {
    const angleDeg = minAng + i * stepAng;
    const angleRad = (angleDeg * Math.PI) / 180;
    const cosTheta = Math.cos(angleRad);

    // Compute Scattering Amplitudes f(theta) and g(theta) via Legendre Polynomial summation
    let reF = 0;
    let imF = 0;
    let reG = 0;
    let imG = 0;

    // Associated Legendre polynomial P_l^0(cos theta) and P_l^1(cos theta) recurrence
    let pLPrev2 = 0;
    let pLPrev1 = 1; // P_0 = 1
    let pL = 1;

    let pL1Prev2 = 0;
    let pL1Prev1 = 0; // P_0^1 = 0
    let pL1 = 0;

    const sinTheta = Math.sin(angleRad);

    for (let l = 0; l <= maxL; l++) {
      if (l === 0) {
        pL = 1;
        pL1 = 0;
      } else if (l === 1) {
        pL = cosTheta;
        pL1 = sinTheta;
      } else {
        pL = ((2 * l - 1) * cosTheta * pLPrev1 - (l - 1) * pLPrev2) / l;
        pL1 = ((2 * l - 1) * cosTheta * pL1Prev1 - l * pL1Prev2) / (l - 1);
      }

      pLPrev2 = pLPrev1;
      pLPrev1 = pL;

      pL1Prev2 = pL1Prev1;
      pL1Prev1 = pL1;

      // Retrieve phase shifts for kappa = -(l+1) [j = l + 1/2] and kappa = l [j = l - 1/2]
      const psPlus = phaseShifts.find((p) => p.kappa === -l - 1);
      const psMinus = l > 0 ? phaseShifts.find((p) => p.kappa === l) : null;

      const dPlusRe = psPlus ? psPlus.deltaRe : 0;
      const dPlusIm = psPlus ? psPlus.deltaIm : 0;
      const dMinusRe = psMinus ? psMinus.deltaRe : 0;
      const dMinusIm = psMinus ? psMinus.deltaIm : 0;

      // e^(2i delta) - 1 terms
      const expPlusRe = Math.exp(-2 * dPlusIm) * Math.cos(2 * dPlusRe) - 1;
      const expPlusIm = Math.exp(-2 * dPlusIm) * Math.sin(2 * dPlusRe);

      const expMinusRe = Math.exp(-2 * dMinusIm) * Math.cos(2 * dMinusRe) - 1;
      const expMinusIm = Math.exp(-2 * dMinusIm) * Math.sin(2 * dMinusRe);

      // Direct amplitude f(theta) contribution
      const termF_Re = (l + 1) * expPlusRe + l * expMinusRe;
      const termF_Im = (l + 1) * expPlusIm + l * expMinusIm;

      reF += termF_Re * pL;
      imF += termF_Im * pL;

      // Spin-flip amplitude g(theta) contribution
      const termG_Re = expMinusRe - expPlusRe;
      const termG_Im = expMinusIm - expPlusIm;

      reG += termG_Re * pL1;
      imG += termG_Im * pL1;
    }

    // Multiply by 1 / (2 i k) = -i / (2 k)
    const factorK = 1 / (2 * kWaveVector);
    const finalReF = imF * factorK;
    const finalImF = -reF * factorK;

    const finalReG = imG * factorK;
    const finalImG = -reG * factorK;

    // Differential Cross Section (DCS) = |f|^2 + |g|^2
    const dcsAu = finalReF * finalReF + finalImF * finalImF + finalReG * finalReG + finalImG * finalImG;
    const dcsCm2 = dcsAu * BOHR_SQ_TO_CM2;
    const dcsAngstrom2 = dcsAu * BOHR_SQ_TO_ANGSTROM2;

    // Sherman Function S(theta) = 2 Im(f g*) / (|f|^2 + |g|^2)
    // Im(f g*) = Im( (reF + i imF) * (reG - i imG) ) = imF * reG - reF * imG
    const imFGstar = finalImF * finalReG - finalReF * finalImG;
    const reFGstar = finalReF * finalReG + finalImF * finalImG;

    const shermanS = dcsAu > 1e-30 ? (2 * imFGstar) / dcsAu : 0;
    const spinT = dcsAu > 1e-30 ? (finalReF * finalReF + finalImF * finalImF - (finalReG * finalReG + finalImG * finalImG)) / dcsAu : 1;
    const spinU = dcsAu > 1e-30 ? (2 * reFGstar) / dcsAu : 0;

    scatteringData.push({
      angleDeg,
      angleRad,
      dcsAu,
      dcsCm2,
      dcsAngstrom2,
      shermanS: Math.max(-1, Math.min(1, shermanS)),
      spinT: Math.max(-1, Math.min(1, spinT)),
      spinU: Math.max(-1, Math.min(1, spinU)),
      reF: finalReF,
      imF: finalImF,
      reG: finalReG,
      imG: finalImG,
    });

    // Numerical Quadrature Integration for Total Cross Sections
    if (i > 0) {
      const prev = scatteringData[i - 1];
      const dAngRad = angleRad - prev.angleRad;
      const midSin = Math.sin((angleRad + prev.angleRad) / 2);
      const midCos = Math.cos((angleRad + prev.angleRad) / 2);
      const midDcs = (dcsAu + prev.dcsAu) / 2;

      const dOmega = 2 * Math.PI * midSin * dAngRad;

      totalSigmaElAu += midDcs * dOmega;
      totalSigma1Au += midDcs * (1 - midCos) * dOmega;
      totalSigma2Au += midDcs * (1.5 * (1 - midCos * midCos)) * dOmega;
    }
  }

  // Calculate Absorption cross section if MABS=1
  if (params.absorptionModel === 'staszewska-lda') {
    totalSigmaAbsAu = totalSigmaElAu * 0.15;
  }

  const elsepaInputFileText = generateElsepaInputFile(params);
  const endTime = performance.now();

  return {
    params,
    element,
    scatteringData,
    potentialProfile,
    phaseShifts,
    summary: {
      sigmaElAu: totalSigmaElAu,
      sigmaElCm2: totalSigmaElAu * BOHR_SQ_TO_CM2,
      sigma1Au: totalSigma1Au,
      sigma1Cm2: totalSigma1Au * BOHR_SQ_TO_CM2,
      sigma2Au: totalSigma2Au,
      sigmaAbsAu: totalSigmaAbsAu,
      kWaveVector,
      gammaRelativistic,
      betaRelativistic,
      maxL,
      computationTimeMs: Math.round((endTime - startTime) * 10) / 10,
      engineUsed: 'typescript-dirac-solver',
    },
    elsepaInputFileText,
  };
}

/**
 * Calculates energy sweep spectrum (total cross section vs kinetic energy)
 */
export function runEnergySweep(
  baseParams: ElsepaInputParams,
  energiesEv: number[]
): EnergySweepPoint[] {
  const sweep: EnergySweepPoint[] = [];

  for (const energyEv of energiesEv) {
    const p = { ...baseParams, energyEv, minAngle: 0, maxAngle: 180, angleStep: 2.0 };
    const res = runDiracPartialWaveSimulation(p);

    let shermanMin = 0;
    let shermanMax = 0;
    res.scatteringData.forEach((pt) => {
      if (pt.shermanS < shermanMin) shermanMin = pt.shermanS;
      if (pt.shermanS > shermanMax) shermanMax = pt.shermanS;
    });

    sweep.push({
      energyEv,
      sigmaElAu: res.summary.sigmaElAu,
      sigmaElCm2: res.summary.sigmaElCm2,
      sigma1Au: res.summary.sigma1Au,
      sigma2Au: res.summary.sigma2Au,
      sigmaAbsAu: res.summary.sigmaAbsAu,
      shermanPeakMin: shermanMin,
      shermanPeakMax: shermanMax,
    });
  }

  return sweep;
}
